# Generated by Django 5.2.4 on 2025-12-05 11:42

from django.conf import settings
from django.db import migrations, models


def noop(apps, schema_editor):
    """No-op function for migrations that are already applied."""
    pass


class Migration(migrations.Migration):
    """
    This migration is for SQLite compatibility only.
    On Oracle, these changes were already applied in migration 0003.
    """

    dependencies = [
        ('internal_chat', '0009_add_group_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # These operations are skipped on Oracle (already applied in 0003)
        # but needed for SQLite where 0003 used RunPython
        migrations.RunPython(noop, noop),  # Placeholder - actual work done in 0003
    ]
