# Generated by Django 5.2.4 on 2025-12-03 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the quick link (max 100 characters)', max_length=100)),
                ('icon_data', models.BinaryField(blank=True, help_text='Icon image data stored as BLOB (PNG, JPG, SVG, WEBP - max 5MB)', null=True)),
                ('icon_mime_type', models.CharField(blank=True, help_text='MIME type of the icon: image/png, image/jpeg, image/svg+xml, image/webp', max_length=50, null=True)),
                ('icon_original_filename', models.CharField(blank=True, help_text='Original filename of uploaded icon (sanitized)', max_length=255, null=True)),
                ('redirect_url', models.CharField(help_text='External URL to redirect to when clicking the link', max_length=1000, validators=[django.core.validators.URLValidator()])),
                ('position', models.IntegerField(db_index=True, default=0, help_text='Display order position (0-based, lower values appear first)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the link is visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp (UAE timezone)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (UAE timezone)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this quick link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quicklinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['position', '-created_at'], name='quicklinks__positio_9558c3_idx'), models.Index(fields=['is_active', 'position'], name='quicklinks__is_acti_bc650e_idx')],
            },
        ),
    ]
