# Generated by Django 5.2.4 on 2025-12-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuickLinkPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Whether the user has pinned this quick link')),
                ('pin_order', models.IntegerField(default=0, help_text='Order among pinned items (lower = first)')),
                ('last_accessed_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time user clicked/accessed this link', null=True)),
                ('click_count', models.IntegerField(default=0, help_text='Total click count for this link by this user')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this preference was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('quicklink', models.ForeignKey(help_text='Quick link this preference applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='quicklinks.quicklink')),
                ('user', models.ForeignKey(help_text='User who owns this preference', on_delete=django.db.models.deletion.CASCADE, related_name='quicklink_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Quick Link Preference',
                'verbose_name_plural': 'User Quick Link Preferences',
                'ordering': ['-is_pinned', 'pin_order', '-last_accessed_at'],
                'indexes': [models.Index(fields=['user', '-is_pinned', 'pin_order'], name='quicklinks__user_id_b68b6d_idx'), models.Index(fields=['user', '-last_accessed_at'], name='quicklinks__user_id_731cb1_idx')],
                'unique_together': {('user', 'quicklink')},
            },
        ),
    ]
