# Generated by Django 5.2.4 on 2025-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_replace_ip_with_mac_address'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='deviceresponse',
        #     name='ip_address',
        # ),
        migrations.AlterField(
            model_name='question',
            name='CSAT_Calculate',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if this question is used for CSAT calculation (only valid for single_choice, rating, yes_no)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='NPS_Calculate',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if this question is used for NPS calculation (only valid for rating questions)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='semantic_tag',
            field=models.CharField(choices=[('none', 'None'), ('nps', 'NPS'), ('csat', 'CSAT')], db_index=True, default='none', help_text='Semantic tag for analytics optimization (fallback if Calculate flags not set)', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option_text_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of option text for efficient matching', max_length=64),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['option_text_hash'], name='option_text_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['satisfaction_value'], name='option_satisfaction_idx'),
        ),
    ]
