# Generated by Django 5.2.4 on 2025-12-05 11:42

from django.db import migrations, models


def remove_ip_address_if_exists(apps, schema_editor):
    """Remove ip_address column if it exists (may already be removed or renamed)."""
    if schema_editor.connection.vendor == 'oracle':
        cursor = schema_editor.connection.cursor()
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) FROM user_tab_columns 
            WHERE table_name = 'SURVEYS_DEVICE_RESPONSE' 
            AND column_name = 'IP_ADDRESS'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute('ALTER TABLE SURVEYS_DEVICE_RESPONSE DROP COLUMN IP_ADDRESS')


def noop(apps, schema_editor):
    """No-op for reverse operations."""
    pass


class Migration(migrations.Migration):
    """
    This migration handles cleanup that may have been partially done in previous migrations.
    Uses safe operations that check existence before acting.
    """

    dependencies = [
        ('surveys', '0021_remove_deviceresponse_ip_address_and_more'),
    ]

    operations = [
        # Safe removal of ip_address (checks existence first)
        migrations.RunPython(remove_ip_address_if_exists, noop),
        # Other operations already applied in 0021 via RunPython
    ]
